### ISSUE TITLE
Error starting ApplicationContext

### ISSUE THREAD

**Issue by mbeghi** [1element/sc#1]
I need to solve this error. Can you help me, please?

Thanks, 
M.
[output.txt](https://github.com/1element/sc/files/1467219/output.txt)

**Comment by 1element** [comment]
Hi M.,

this is the interesting part of the logfile:

```
org.hsqldb.HsqlException: Database lock acquisition failure: 
lockFile: org.hsqldb.persist.LockFile@f384f3ec[file =/home/surveillance/db/surveillance.db.lck, exists=false, locked=false, valid=false, ] 
method: openRAF reason: java.io.FileNotFoundException: /home/surveillance/db/surveillance.db.lck (No such file or directory)
```

Please check the value of `spring.datasource.url` in your `application.properties` file. 

`/home/surveillance/db/` is probably a non-existing directory on your system?

Best regards
Sebastian

**Comment by 1element** [comment]
I will close this issue. If you have any further problems or questions feel free to open another issue.
